seed: 42
device: cuda
save_dir: outputs/runs
eps: 10
model:
  name: dino_vitb16
  stride: 16
  layer: 10
  facet: key
  attn_layer: 10
data:
  root: datasets/imagenet2012
  batch_size: 32
  shuffle: true
  num_workers: 4
  pin_memory: true
train:
  epochs: 1
  lr: 0.0002
  log_every_n_steps: 2000
